Hw01
laschishin/2024-01-otus-spring-laschishin pull request #1
Opened 2024-02-11 13:49 UTC by laschishin

2024-02-13 16:58 UTC, VladimirMagerov requested changes

2024-02-13 16:58 UTC, VladimirMagerov commented on hw01/src/main/java/ru/otus/hw/service/UtilsServiceImpl.java
> +            throw new IllegalArgumentException("File not found: " + fileName);
В данном случае предлагаю использовать тот же `QuestionReadException`, так как `IllegalArgumentException` тут не совсем подходит - он мог бы подойти в случае, например, если есть определённые правила относительно названия файла, или его расширения, и мы могли бы это проверить в начале метода, до выполнения основной логики.

2024-02-13 16:58 UTC, VladimirMagerov commented on hw01/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +import static org.mockito.Mockito.*;
Wildcard импорты зачастую малоинформативны и потенциально могут приводить к конфликту имён, предлагаю использовать отдельные импорты для каждой импортируемой единицы.

2024-02-13 16:58 UTC, VladimirMagerov commented on hw01/src/test/java/ru/otus/hw/service/UtilsServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Аналогично - предлагаю разбить на отдельные.

2024-02-13 16:58 UTC, VladimirMagerov commented on hw01/src/test/java/ru/otus/hw/domain/QuestionTest.java
> +    void shouldHaveCorrectConstructor() {
Тесты на конструкторы обычно не пишут, так как в конструкторе должна происходить только инициализация объекта, а всё его поведение должно быть в его public методах. Тестируется именно поведение.

2024-02-13 16:58 UTC, VladimirMagerov commented on hw01/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        verify(testFileNameProvider, times(1)).getTestFileName();
Параметр `times` не обязательно указывать, если количество ожидаемых вызовов равно единице.

2024-02-13 17:08 UTC, VladimirMagerov approved these changes

2024-02-14 13:29 UTC, laschishin commented on hw01/src/main/java/ru/otus/hw/service/UtilsServiceImpl.java
> +            throw new IllegalArgumentException("File not found: " + fileName);
Сделал, спасибо

2024-02-14 13:31 UTC, laschishin commented on hw01/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +import static org.mockito.Mockito.*;
Ок, сделал

2024-02-14 13:32 UTC, laschishin commented on hw01/src/test/java/ru/otus/hw/service/UtilsServiceImplTest.java
> +import static org.junit.jupiter.api.Assertions.*;
Сделал

2024-02-14 13:33 UTC, laschishin commented on hw01/src/test/java/ru/otus/hw/domain/QuestionTest.java
> +    void shouldHaveCorrectConstructor() {
Ок, убрал тест

2024-02-14 13:34 UTC, laschishin commented on hw01/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        verify(testFileNameProvider, times(1)).getTestFileName();
Думал так информативнее. Убрал

2024-02-15 07:22 UTC, merged