Hw02
laschishin/2024-01-otus-spring-laschishin pull request #2
Opened 2024-02-20 10:41 UTC by laschishin

2024-02-22 16:48 UTC, VladimirMagerov requested changes

2024-02-22 16:48 UTC, VladimirMagerov commented on hw02/pom.xml
> +    <artifactId>hw01-xml-config</artifactId>
Мелочь, но всё же - это уже hw02, получается)

2024-02-22 16:48 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        TestService testService = new TestServiceImpl(ioService, questionDao, questionService);
Правильнее будет оставить внедрение моков-зависимостей самому Mockito, а именно заменить ручное создание `testService` на его декларирование в самом классе, например так:
   `@InjectMocks`
    `TestServiceImpl testService;`

2024-02-22 16:48 UTC, VladimirMagerov commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        String mockedCSVContent = """
Совет - гораздо удобнее будет, если данные для тестов будут лежать в отдельном файле, а не храниться в самом классе теста. В данном случае это практически ни на что не влияет, но если представить, что нам надо тестировать намного больший объём данных (например, 100+ вопросов), хранить их в самом классе уже будет совсем не удобно. А если сразу вынести это всё в отдельный файл, управлять данными будет гораздо удобнее.

2024-02-22 16:50 UTC, VladimirMagerov approved these changes

2024-02-25 15:01 UTC, laschishin commented on hw02/pom.xml
> +    <artifactId>hw01-xml-config</artifactId>
Поправил

2024-02-25 15:50 UTC, laschishin commented on hw02/src/test/java/ru/otus/hw/service/TestServiceImplTest.java
> +        TestService testService = new TestServiceImpl(ioService, questionDao, questionService);
Сделал, спасибо

2024-02-25 15:54 UTC, laschishin commented on hw02/src/test/java/ru/otus/hw/dao/CsvQuestionDaoTest.java
> +        String mockedCSVContent = """
Ок, сделал

2024-02-25 15:56 UTC, merged