Hw05
laschishin/2024-01-otus-spring-laschishin pull request #5
Opened 2024-03-22 19:17 UTC by laschishin

2024-03-27 19:03 UTC, VladimirMagerov requested changes

2024-03-27 19:03 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                  left join genres g on g.id = b.genre_id
Почему использовали именно left join, а не более подходящий inner join?

2024-03-27 19:03 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                select a.id
Не хотите ли попробовать получить всю информацию о книге + жанре + авторах за один запрос с несколькими join-ами? Соединить всё в одном запросе, дальше из результата составить объект через реализацию ResultSetExtractor, и собрать там полный объект?

2024-03-28 20:36 UTC, laschishin commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                  left join genres g on g.id = b.genre_id
Насколько я понял задание, книга является главной сущностью и жанр/автор может отсутствовать. Об этом говорит `nullable` поле `author_id` в заготовке. Если понял неправильно, переделаю все `left` на `inner`

2024-03-28 21:15 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                  left join genres g on g.id = b.genre_id
Окей, тогда переделывать ничего не надо)

2024-03-28 21:29 UTC, laschishin commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +                select a.id
Да, разбил на два, чтобы не гонять лишние данные по сети. А сейчас вижу, что получилась экономия на спичках. Сделал, спасибо

2024-03-30 13:33 UTC, merged