Hw06
laschishin/2024-01-otus-spring-laschishin pull request #6
Opened 2024-05-07 20:34 UTC by laschishin

2024-05-14 22:54 UTC, VladimirMagerov requested changes

2024-05-14 22:54 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/services/AuthorServiceImpl.java
> +    @Override
не хватает `@Transactional`

2024-05-14 22:54 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/services/BookCommentServiceImpl.java
> +    @Override
и тут тоже

2024-05-14 22:54 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/services/BookServiceImpl.java
> +    @Override
и тут)

2024-05-15 08:37 UTC, laschishin commented on hw06/src/main/java/ru/otus/hw/services/AuthorServiceImpl.java
> +    @Override
добавил

2024-05-15 08:37 UTC, laschishin commented on hw06/src/main/java/ru/otus/hw/services/BookCommentServiceImpl.java
> +    @Override
добавил

2024-05-15 08:37 UTC, laschishin commented on hw06/src/main/java/ru/otus/hw/services/BookServiceImpl.java
> +    @Override
добавил

2024-05-15 21:59 UTC, VladimirMagerov approved these changes

2024-05-16 07:33 UTC, merged